# ubuntu, windows, macos
# node 10.x, 12.x
# npm install
# node tests/all-tests.js

name: Node.js CI

on: [push, pull_request]

jobs:
    build:
        name: Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix: 
              os: [ubuntu-18.04, windows-latest, macos-latest]
              node-version: [10.x, 12.x]
        env:
            CI: true
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  fetch-depth: 1
            - name: Versions
              run: |
                  echo Node:
                  node --version
                  echo NPM:
                  npm --version
            - name: NPM install (ci)
              run: npm ci
            - name: Lint
              run: npx grunt lint
            - name: Test
              run: node tests/all-tests.js
